<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="9bd765f9e082" failures="1" tests="3" name="user_sam" time="10.498" errors="0" timestamp="2023-12-02T12:52:41 GMT">
  <testcase classname="tests.VendorPortalTest" name="userRegistrationTest" time="1.911"/>
  <testcase classname="tests.VendorPortalTest" name="dashbordTest" time="3.806">
    <failure type="java.lang.AssertionError" message="expected [80] but found [8]">
      <![CDATA[java.lang.AssertionError: expected [80] but found [8]
at tests.VendorPortalTest.dashbordTest(VendorPortalTest.java:48)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- dashbordTest -->
  <testcase classname="tests.VendorPortalTest" name="LogOut" time="0.0">
    <skipped/>
  </testcase> <!-- LogOut -->
</testsuite> <!-- user_sam -->
